### ISSUE TITLE
CW projects files missing

### ISSUE THREAD

**Issue by angel77777** [uTasker/uTasker-Kinetis#1]
Following this guide 
http://www.utasker.com/kinetis/compilers.html
we've tried to import uTasker project in CW.
In the .settings directory we don't find any .project or .cproject file that the guide ask us to find.
We've downloaded the files directly from githun webapge.
Is there another repository to link?

Thanks,
regards
Samuele

**Comment by angel77777** [comment]
Here a screenshot of the warning:
https://www.dropbox.com/s/fbxiwzvgdf3siig/warning%20CW.jpg?dl=0

**Comment by uTasker** [comment]
Hi Samuele
I think that you have not correctly followed the first 2 steps in the guide (copy below).
You need to locate the CW project in "\Applications\uTaskerV1.4\KinetisCodeWarrior\ProjectSettings" and copy that to the root. I just checked and these are in the repository.
Regards
Mark

Step 1. To prepare the CodeWarrior import (as opposed to KDS or Atollic) start by deleting the directory ".settings" in the root directory of the µTasker project (the root directory the folder where the project was extracted to including directories "uTasker", "Hardware", "Applications" etc.) as well as other files at this location which begin with a '.' (eg. ".cproject") since these may be for alternative Eclipse based environments.

Step 2. Now copy the CodeWarrior project settings from the folder \Applications\uTaskerV1.4\KinetisCodeWarrior\Project_Settings to the root (these are the directory ".settings" and files ".cproject", ".cwGeneratedFileSetLog", ".project" etc.).
There is also a read.me file in the project root directory explaining the procedure and why it is necessary. If you already know and are sure that the CodeWarrior files are located in the root these steps are of course not necessary.

**Comment by huyrua291996** [comment]
Hi @uTasker 
I still got the error like @angel77777  and the Settings has nothing in CW10.7

**Comment by uTasker** [comment]
Hi
It looks like **.project**, **.cproject** (and .cwGeneratedFileSetLog) were really missing in the  directory!
They have been added now.
Sorry and thanks
Mark

**Comment by huyrua291996** [comment]
Thanks you
